-- Final additions to the initial table definitions. No users or demo records.
ALTER TABLE public.users DROP COLUMN team_ids;
ALTER TABLE public.users
  ALTER COLUMN active SET DEFAULT false,
  ALTER COLUMN must_change_password SET DEFAULT true,
  ADD COLUMN external_id text,
  ADD COLUMN source_system text,
  ADD COLUMN is_provisional boolean NOT NULL DEFAULT false;
ALTER TABLE public.teams ADD COLUMN icon text DEFAULT 'Shield';
ALTER TABLE public.access_requests ADD COLUMN rejection_reason text;
ALTER TABLE public.monitorias
  ADD COLUMN display_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  ADD COLUMN started_at timestamptz,
  ADD COLUMN finished_at timestamptz,
  ADD COLUMN concluded_at timestamptz,
  ADD CONSTRAINT monitorias_score_check CHECK (score BETWEEN 0 AND 100),
  ADD CONSTRAINT monitorias_status_check CHECK (status IN ('pendente_revisao','em_contestacao','aguardando_gestor_suporte','aguardando_gestor_qualidade','concluida','contestacao_aceita','contestacao_negada','finalizada_alterada','reavaliacao_solicitada')),
  ADD CONSTRAINT monitorias_resolution_check CHECK (resolution_type IN ('human','automatic')),
  ADD CONSTRAINT monitorias_contestation_check CHECK (contestation_result IN ('approved','rejected','pending'));
CREATE INDEX users_external_identity_idx ON public.users(source_system,external_id);
CREATE INDEX user_teams_team_idx ON public.user_teams(team_id);
CREATE INDEX monitorias_team_idx ON public.monitorias(team_id);
CREATE INDEX monitorias_form_idx ON public.monitorias(form_id) WHERE active;
CREATE INDEX monitorias_evaluated_idx ON public.monitorias(evaluated_id,score) WHERE active;
CREATE INDEX monitorias_evaluator_idx ON public.monitorias(evaluator_id) WHERE active;
CREATE INDEX monitorias_deadline_idx ON public.monitorias(action_deadline_at) WHERE active AND status NOT IN ('concluida','finalizada_alterada');
CREATE INDEX access_requests_email_status_idx ON public.access_requests(lower(email),status);

CREATE SCHEMA _private;
REVOKE ALL ON SCHEMA _private FROM public,anon;
GRANT USAGE ON SCHEMA _private TO authenticated;
CREATE FUNCTION _private.current_active_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT role FROM public.users WHERE id = (SELECT auth.uid()) AND active;
$$;
CREATE FUNCTION _private.is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT coalesce(_private.current_active_role() = 'admin', false);
$$;
REVOKE ALL ON FUNCTION _private.current_active_role(),_private.is_admin() FROM public,anon;
GRANT EXECUTE ON FUNCTION _private.current_active_role(),_private.is_admin() TO authenticated;

DO $$ DECLARE tbl text; BEGIN
  FOREACH tbl IN ARRAY ARRAY['users','teams','forms','monitorias','access_requests','quality_configs','dissatisfaction_fields','user_teams','user_preferences','business_hours','holidays'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',tbl);
  END LOOP;
END $$;
-- Permissive SELECT policies are bounded by the restrictive hardening migration.
CREATE POLICY users_select ON public.users FOR SELECT TO authenticated USING (true);
CREATE POLICY users_admin_write ON public.users FOR ALL TO authenticated USING (_private.is_admin()) WITH CHECK (_private.is_admin());
CREATE POLICY user_teams_select ON public.user_teams FOR SELECT TO authenticated USING (true);
CREATE POLICY user_teams_admin_write ON public.user_teams FOR ALL TO authenticated USING (_private.is_admin()) WITH CHECK (_private.is_admin());
CREATE POLICY teams_select ON public.teams FOR SELECT TO authenticated USING (true);
CREATE POLICY teams_admin_write ON public.teams FOR ALL TO authenticated USING (_private.is_admin()) WITH CHECK (_private.is_admin());
DO $$ DECLARE tbl text; BEGIN
  FOREACH tbl IN ARRAY ARRAY['forms','quality_configs','dissatisfaction_fields','business_hours','holidays'] LOOP
    EXECUTE format('CREATE POLICY active_read ON public.%I FOR SELECT TO authenticated USING (_private.current_active_role() IS NOT NULL)',tbl);
    EXECUTE format('CREATE POLICY quality_write ON public.%I FOR ALL TO authenticated USING (_private.current_active_role() IN (''admin'',''gestor_qualidade'')) WITH CHECK (_private.current_active_role() IN (''admin'',''gestor_qualidade''))',tbl);
  END LOOP;
END $$;
CREATE POLICY access_requests_admin_read ON public.access_requests FOR SELECT TO authenticated USING (_private.current_active_role() IN ('admin','gestor_qualidade','gestor_suporte'));
CREATE POLICY access_requests_admin_update ON public.access_requests FOR UPDATE TO authenticated USING (_private.current_active_role() IN ('admin','gestor_qualidade')) WITH CHECK (_private.current_active_role() IN ('admin','gestor_qualidade'));
CREATE POLICY user_preferences_self ON public.user_preferences FOR ALL TO authenticated USING (user_id = (SELECT auth.uid()) AND _private.current_active_role() IS NOT NULL) WITH CHECK (user_id = (SELECT auth.uid()) AND _private.current_active_role() IS NOT NULL);

CREATE FUNCTION public.update_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;
DO $$ DECLARE tbl text; BEGIN
  FOREACH tbl IN ARRAY ARRAY['monitorias','quality_configs','user_preferences'] LOOP
    EXECUTE format('CREATE TRIGGER touch_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.update_updated_at()',tbl);
  END LOOP;
END $$;
